name: Playwright CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  install_and_test:
    runs-on: ubuntu-latest
    
    steps:
      # Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v3
        
      # Set up Node.js (using version 16)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # Install dependencies
      - name: Install dependencies
        run: npm install
        
      # Run Playwright tests
      - name: Run Playwright tests
        run: npm test
        env:
          PWDEBUG: '1'  # Enable Playwright debugging

      # Upload screenshots, videos, and traces as artifacts
      - name: Upload Playwright artifacts
        if: always()  # Ensure this runs even if the test fails
        uses: actions/upload-artifact@v3
        with:
          name: playwright-artifacts
          path: |
            **/test-results/**/*.png
            **/test-results/**/*.mp4
            **/test-results/**/*.zip
