name: Node.js CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  install_and_test:
    runs-on: ubuntu-latest
    
    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3
        
      # Set up Node.js (version 16 in this case)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
        
      # Navigate to the directory containing package.json (if needed)
      - name: Change directory to client
        run: cd client  # Modify this line if your package.json is in a different subfolder

      # Install dependencies
      - name: Install dependencies
        run: npm install
        
      # Print a success message to confirm the workflow is running
      - name: Print success message
        run: echo "GitHub Action is successfully running on Ubuntu!"
