name: Node.js CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  install_and_test:
    runs-on: ubuntu-latest
    
    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3
        
      # Set up Node.js (version 16 in this case)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
        
      # List the files in the root directory for debugging
      - name: List files in the root directory
        run: ls -al

      # If necessary, navigate to the directory containing package.json (modify as needed)
      - name: Change directory to client (if it exists)
        run: |
          if [ -d "client" ]; then
            cd client
          else
            echo "Client directory not found!"
          fi

      # Install dependencies
      - name: Install dependencies
        run: npm install
        
      # Print a success message to confirm the workflow is running
      - name: Print success message
        run: echo "GitHub Action is successfully running on Ubuntu!"
